#include<stdio.h>
int main()
{
    int t,n,i,j,num[100],pressed[100];
    scanf("%d",&t);
    for(i=1;i<=t;i++)
    {
        scanf("%d",&n);
        for(j=0;j<n;j++)
        {
            scanf("%d",&num[j]);
        }
        for(j=0;j<n;j++)
        {
            scanf("%d",&pressed[j]);
        }
        for(j=0;j<n;j++)
        {
            if(num[j]==1&&pressed[j]==1)
                printf(".");
            if(num[j]==1&&pressed[j]==2)
                printf(",");
            if(num[j]==1&&pressed[j]==3)
                printf("?");
            if(num[j]==1&&pressed[j]==4)
                printf("%c",34);
            if(num[j]==2&&pressed[j]==1)
                printf("a");
            if(num[j]==2&&pressed[j]==2)
            printf("b");
            if(num[j]==2&&pressed[j]==3)
            printf("c");
            if(num[j]==3&&pressed[j]==1)
            printf("d");
            if(num[j]==3&&pressed[j]==2)
            printf("e");
            if(num[j]==3&&pressed[j]==3)
            printf("f");
            if(num[j]==4&&pressed[j]==1)
            printf("g");
            if(num[j]==4&&pressed[j]==2)
            printf("h");
            if(num[j]==4&&pressed[j]==3)
            printf("i");
            if(num[j]==5&&pressed[j]==1)
            printf("j");
            if(num[j]==5&&pressed[j]==2)
            printf("k");
            if(num[j]==5&&pressed[j]==3)
            printf("l");
            if(num[j]==6&&pressed[j]==1)
            printf("m");
            if(num[j]==6&&pressed[j]==2)
            printf("n");
            if(num[j]==6&&pressed[j]==3)
            printf("o");
            if(num[j]==7&&pressed[j]==1)
            printf("p");
            if(num[j]==7&&pressed[j]==2)
            printf("q");
            if(num[j]==7&&pressed[j]==3)
            printf("r");
            if(num[j]==7&&pressed[j]==4)
            printf("s");
            if(num[j]==8&&pressed[j]==1)
            printf("t");
            if(num[j]==8&&pressed[j]==2)
            printf("u");
            if(num[j]==8&&pressed[j]==3)
            printf("v");
            if(num[j]==9&&pressed[j]==1)
            printf("w");
            if(num[j]==9&&pressed[j]==2)
            printf("x");
            if(num[j]==9&&pressed[j]==3)
            printf("y");
            if(num[j]==9&&pressed[j]==4)
            printf("z");
            if(num[j]==0&&pressed[j]==1)
            printf(" ");
        }
        printf("\n");
    }
}
